Homework 2
================
Shangsi Lin
2022/10/01

``` r
library(tidyverse)
library(readxl)
```

## Problem 1

Import data from `NYC_Transit_Subway_Entrance_And_Exit_Data.csv`. Then
clean variable names and selects the interested column of variables.
Using the `recode()` argument to change the entry variable from `YES` /
`NO` to a logical variable. Also change the route 8-11 data type from
double to character as the route 1-7 data.

``` r
transit_df = 
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))
```

These data are not tidy, after the cleaning above, the current dataset
contains variables including line, station name, station latitude,
station longitude, route information, entry, exit only or not, vending,
entrance type, and ADA compliance. The dataset dimension is 1868 x 20.
It would be helpful to change rount numbers and route as variables for
investigations interested on specific routes.

To find out the number of unique stations, select station name and line
and use `distinct()` to find all unique combinations that each
represents a unique station. The number of rows represent the number of
unique stations.

``` r
transit_df %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

Turns out, there are 465 unique stations.

To find out the number of ADA compliant stations, filter `ada == TRUE`
first and then select unique stations the same as before. The number of
rows represent the number of ADA compliant stations.

``` r
transit_df %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

Turns out, there are 84 ADA compliant stations.

To find out the proportion of station entrances / exits without vending
allow entrance, first filter stations that don’t allow vending, and then
take the mean of the `entry` variable. The result is the parameter of
interest.

``` r
transit_df %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

Turns out, the proportion of station entrances / exits without vending
allow entrance is about 0.377

Reformat data so that route number and route name are distinct
variables, then identify stations that serve the A train and how many of
those are ADA compliant using the `filter`, `select`, and `distinct`
arguments.

``` r
reformat_df = transit_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route") 

reformat_df %>%   
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
reformat_df %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

Turns out, there are 60 stations that serve the A train and 17 stations
that serve the A train while being ADA compliant.

## Problem 2

Import two data sheets from
`Trash-Wheel-Collection-Totals-7-2020-2.xlsx`, clean the names od the
variables and filter out only dumpster-specific data. Round the number
of sports balls to the nearest integer and converts the result to an
integer variable. Rename variable name “dumpster” into “dumpster_number”
for clarity, and used brackets to mark units for weight and volume. Add
a new variable called `wheel_name` to keep track of which trash wheel
does the data belong to.

``` r
mr_trash_df = 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = 1, range = "A2:N549") %>% 
  janitor::clean_names() %>% 
  filter(dumpster != "NA") %>% 
  mutate(sports_balls = as.integer(round(sports_balls)),
         year = as.double(year)) %>% 
  mutate(wheel_name = "mr_trash") %>% 
  rename("dumpster_number" = dumpster,
         "weight(tons)" = weight_tons,
         "volume(cubic yards)" = volume_cubic_yards)

professor_trash_df = 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M96") %>%
  janitor::clean_names() %>% 
  filter(dumpster != "NA") %>% 
  mutate(wheel_name = "professor_trash") %>% 
  rename("dumpster_number" = dumpster,
         "weight(tons)" = weight_tons,
         "volume(cubic yards)" = volume_cubic_yards)
```

Combine both data sheets to produce a single tidy dataset, .

``` r
trash_wheel_df = 
  bind_rows(mr_trash_df, professor_trash_df) %>% 
  arrange(dumpster_number, increasing = TRUE)
trash_wheel_df
```

    ## # A tibble: 641 × 15
    ##    dumpster_nu…¹ month  year date                weigh…² volum…³ plast…⁴ polys…⁵
    ##            <dbl> <chr> <dbl> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>
    ##  1             1 May    2014 2014-05-16 00:00:00    4.31      18    1450    1820
    ##  2             1 Janu…  2017 2017-01-02 00:00:00    1.79      15    1950    6080
    ##  3             2 May    2014 2014-05-16 00:00:00    2.74      13    1120    1030
    ##  4             2 Janu…  2017 2017-01-30 00:00:00    1.58      15    9540   11230
    ##  5             3 May    2014 2014-05-16 00:00:00    3.45      15    2450    3100
    ##  6             3 Febr…  2017 2017-02-26 00:00:00    2.32      18    8350    9210
    ##  7             4 May    2014 2014-05-17 00:00:00    3.1       15    2380    2730
    ##  8             4 Febr…  2017 2017-02-26 00:00:00    3.72      15    8590    1030
    ##  9             5 May    2014 2014-05-17 00:00:00    4.06      18     980     870
    ## 10             5 Febr…  2017 2017-02-28 00:00:00    1.45      15    7830    9950
    ## # … with 631 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, wheel_name <chr>, and abbreviated
    ## #   variable names ¹​dumpster_number, ²​`weight(tons)`, ³​`volume(cubic yards)`,
    ## #   ⁴​plastic_bottles, ⁵​polystyrene

``` r
total_weight = pull(professor_trash_df, "weight(tons)") %>% 
  sum
total_weight
```

    ## [1] 190.12

``` r
filter_df = mr_trash_df %>% 
  filter(year == '2020') 
ball_weight = pull(filter_df, sports_balls) %>% 
  sum
ball_weight
```

    ## [1] 856

The total number of observations in the resulting dataset is 524, key
variables include the dumpster number, the date, weight in tons, volume
in cubic yards, types of trash collected and the amount of each type of
trash collected, and homes the trash wheel powered. The total weight of
trash collected by Professor Trash Wheel is 135.5 tons. The total number
of sports balls collected by Mr.Trash Wheel in 2020 was 856.

## Problem 3

Import and clean the data in pols-month.csv, snp.csv, and
unemployment.csv. For pols_df, break the variable mon into interger
variables year, month, and day. Replace month number with month name,
and created a `president` variable taking values `gop` and `dem`.
Removed `prez_dem`, `prez_gop`, and the dat variable. Cleaned snp_df
with a similar fashion, and organized so variables `year` and `month`
are in the leading columns. Tidy the unemployment data by switching it
from “wide” to “long” format and make the month variable in the same
expression style as the other two data frames.

``` r
pols_df = 
  read_csv('data/fivethirtyeight_datasets/pols-month.csv') %>% 
  janitor::clean_names() %>% 
  separate(mon, c('year', 'month', 'day')) %>% 
  mutate(year = as.integer(year),month = as.integer(month),day = as.integer(day)) %>% 
  mutate(month = month.name[month], president = recode(prez_gop, "1" = "gop", "0" = "dem")) %>% 
  select(-c("prez_gop", "prez_dem", "day")) 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: Unreplaced values treated as NA as `.x` is not compatible.
    ## Please specify replacements exhaustively or supply `.default`.

``` r
snp_df = 
  read_csv("data/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>% 
  separate(date, into = c('month', 'day', 'year')) %>% 
  mutate(year = as.integer(year),month = month.name[as.integer(month)],day = as.integer(day)) %>% 
  select(year, month, everything(),-c("day")) 
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
umemployment_df = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv") %>%
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemployment rate") %>% 
  mutate(month = month.name[match(month,month.abb)]) %>% 
  janitor::clean_names()
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Merge the snp_df into the pols_df, and later merge the umemployment_df
into the result.

``` r
merged_df = left_join(pols_df, snp_df, by = c("year", "month"))
result_df = left_join(merged_df, umemployment_df, by = c("year", "month"))
```

The pols-month dataset contained information about the number of
government officials in different roles belonging to either dem or gop
side at different given times. The snp dataset contained information
about the closing values of the S&P stock index on the associated dates.
The unemployment dataset contained information on the percentage of
unemployment in different months of the associated year.

The resulting dataset has 822 rows and 11 columns. The range of years it
contains is from 1947 to 2015, which is 68 years. The names of key
variables it contains are the year, month, number of government
officials from either gop or dem parties at different roles, the
unemployment rate and the closing values of the S&P stock index on the
associated dates.
